### ISSUE TITLE
Errors when running srt_fix from yt-dlp (2024.04.09) on my mac

### ISSUE THREAD

**Issue by franticht** [bindestriche/srt_fix#15]
username@mac01337 workfolder % yt-dlp --write-auto-subs --sub-langs "en*" --use-postprocessor srt_fix  "[URL TO YOUTUBE VIDEO]"
Traceback (most recent call last):
  File "/opt/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/__init__.py", line 1072, in main
    _exit(*variadic(_real_main(argv)))
                    ^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/__init__.py", line 970, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 789, in __init__
    get_postprocessor(pp_def.pop('key'))(self, **pp_def),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/yt_dlp/postprocessor/__init__.py", line 42, in get_postprocessor
    return globals()[key + 'PP']
           ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'srt_fixPP'

**Comment by bindestriche** [comment]
Maybe you did not copy the plugin to the right place.I had a similar error
when the python file was not at the right place. I have no mac and can't
try it.

ocococococ ***@***.***> schrieb am Di., 28. Mai 2024, 16:48:

**Comment by franticht** [comment]
Not sure if it is related, but maybe it is. I also had another issue with running src_fix standalone on my mac, and I just posted a little update on that one here:

https://github.com/bindestriche/srt_fix/issues/14

**Comment by bindestriche** [comment]
@franticht the [directories for plugins are listed here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installing-plugins)

User Plugins

    ${XDG_CONFIG_HOME}/yt-dlp/plugins/<package name>/yt_dlp_plugins/ (recommended on Linux/macOS)
    ${XDG_CONFIG_HOME}/yt-dlp-plugins/<package name>/yt_dlp_plugins/
    ${APPDATA}/yt-dlp/plugins/<package name>/yt_dlp_plugins/ (recommended on Windows)
    ${APPDATA}/yt-dlp-plugins/<package name>/yt_dlp_plugins/
    ~/.yt-dlp/plugins/<package name>/yt_dlp_plugins/
    ~/yt-dlp-plugins/<package name>/yt_dlp_plugins/

System Plugins

    /etc/yt-dlp/plugins/<package name>/yt_dlp_plugins/
    /etc/yt-dlp-plugins/<package name>/yt_dlp_plugins

**Comment by Tamriel** [comment]
The documentations is quite imprecise.
It works like this:

<img width="630" height="494" alt="Image" src="https://github.com/user-attachments/assets/21431c61-c002-4070-9df4-ebd9fdadefb5" />

**Comment by queste24** [comment]
The linked documentation is pretty okay in my opinion. Direct quote 
```Plugins are loaded from the namespace packages yt_dlp_plugins.extractor and yt_dlp_plugins.postprocessor.

In other words, the file structure on the disk looks something like:

    yt_dlp_plugins/
        extractor/
            myplugin.py
        postprocessor/
            myplugin.py
```
