### ISSUE TITLE
windows11， KeyError: 'srt_fixPP'

### ISSUE THREAD

**Issue by bk111** [bindestriche/srt_fix#17]
python3 -m pip install -U https://github.com/bindestriche/srt_fix/archive/refs/heads/master.zip

C:\Users\dengz\Downloads\0pitch>yt-dlp --write-auto-sub  --sub-lang 'en'  --convert-subs=srt  --restrict-filenames  --no-check-certificates --use-postprocessor srt_fix https://www.youtube.com/watch?
v=jdEaYV5Kq98
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1072, in main
  File "yt_dlp\__init__.py", line 970, in _real_main
  File "yt_dlp\YoutubeDL.py", line 789, in __init__
  File "yt_dlp\postprocessor\__init__.py", line 42, in get_postprocessor
KeyError: 'srt_fixPP'
[30484] Failed to execute script '__main__' due to unhandled exception!

**Comment by bindestriche** [comment]
Thanks for your report.
The pip install does not work correctly, it seems. Please manually install the extension by placing it in [one of the directories.](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#installing-plugins) Alternatively, use one of the utilities I provided. I need to read up on pip to fix it.

**Comment by bashonly** [comment]
> The pip install does not work correctly

@bindestriche PR to fix: https://github.com/bindestriche/srt_fix/pull/24
